//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVenta.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_venta()
        {
            this.detalleVentas = new HashSet<detalleVenta>();
        }
    
        public int idVenta { get; set; }
        public Nullable<int> idDocumento { get; set; }
        public Nullable<int> iDCliente { get; set; }
        public Nullable<int> iDUsuario { get; set; }
        public Nullable<decimal> totalVenta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalleVenta> detalleVentas { get; set; }
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_documento tb_documento { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
    }
}
